// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketTriage.Infrastructure.Persistence;

#nullable disable

namespace TicketTriage.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TriageDbContext))]
    [Migration("20260924101441_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("TicketTriage.Infrastructure.Persistence.TrainingTicketEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("AffectedServices")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Assignee")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Comments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Impact")
                        .HasColumnType("TEXT");

                    b.Property<long>("ImportedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Priority")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resolution")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ServiceTeams")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Urgency")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkType")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("Assignee");

                    b.HasIndex("WorkType");

                    b.ToTable("TrainingTickets", (string)null);
                });

            modelBuilder.Entity("TicketTriage.Infrastructure.Persistence.TriageSuggestionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("EditedJson")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReviewedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewerComment")
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Decision");

                    b.HasIndex("TicketKey");

                    b.ToTable("TriageSuggestions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
